Update README.md
ANU-RSES-Education/EMSC-4033-2022-assignment-Group4 pull request #17
Opened 2022-05-16 07:53 UTC by EdgarLJH

Added MapMaker notebook guide

2022-05-17 01:29 UTC, hma211 requested changes
Looks good, is concise and explains the Map Maker well. 
Just considering that we need to explain how to navigate the repository would it make sense to split the README into two sections using section titles? 
Just thinking that you could add "# MapMaker guide" and "Repository navigation" titles before and after what you've written?

2022-05-17 23:12 UTC, EdgarLJH reviewed
Agreed. Will get to it

2022-05-17 23:13 UTC, EdgarLJH commented
Submitted a new commit with your proposed changes, Holly

2022-05-18 01:55 UTC, hma211 approved these changes

2022-05-18 01:56 UTC, merged